
services:
  pizza-test:
    build: 
      context: .
      dockerfile: pizza_test.Dockerfile
    command: go test -v -run TestHawaiianPizzaExpert
    environment:
      - MODEL_RUNNER_BASE_URL=${MODEL_RUNNER_BASE_URL}
      - MODEL_RUNNER_LLM_CHAT=${MODEL_RUNNER_LLM_CHAT}
    depends_on:
      - download-llm

  star-trek-test:
    build: 
      context: .
      dockerfile: star_trek_test.Dockerfile
    command: go test -v -run TestStarTrekExpert
    environment:
      - MODEL_RUNNER_BASE_URL=${MODEL_RUNNER_BASE_URL}
      - MODEL_RUNNER_LLM_CHAT=${MODEL_RUNNER_LLM_CHAT}
    depends_on:
      - download-llm


  download-llm:
   provider:
     type: model
     options:
       model: ${MODEL_RUNNER_LLM_CHAT}
